# Backbay Imperium - Unit Meshes & Sprites
# Generates 3D unit models using Hunyuan3D, then renders to sprite sheets

schema_version: "1.0"
world_id: backbay_units
world_type: characters
version: "1.0.0"

generator:
  name: "Backbay Imperium - Military & Civilian Units"
  description: |
    Game units spanning Ancient to Modern eras.
    Each unit rendered as 8-direction sprite sheet with idle/walk/attack animations.

build:
  determinism:
    seed: 42
    pythonhashseed: 42

  comfyui:
    host: "${COMFYUI_HOST:-localhost}"
    port: "${COMFYUI_PORT:-8188}"
    timeout_seconds: 300

parameters:
  defaults:
    target_triangles: 10000
    guidance_scale: 6.0
    steps: 50

  style_suffix: ", game character, clean topology, classical art style, heroic proportions"

  sprite_settings:
    directions: 8
    animations: [idle, walk, attack]
    frames_per_animation: 3
    sprite_size: 64

meshes:
  # === ANCIENT ERA ===

  - id: unit_warrior
    name: "Warrior"
    prompt: "ancient tribal warrior, wooden club, leather loincloth, muscular, barbaric fighter"
    category: military
    era: ancient
    class: melee
    tags: [military, melee, basic, ancient]
    stats: { attack: 2, defense: 2, moves: 2, cost: 40 }

  - id: unit_scout
    name: "Scout"
    prompt: "ancient scout, light leather tunic, small bow on back, barefoot, agile runner"
    category: military
    era: ancient
    class: recon
    tags: [military, recon, fast, ancient]
    stats: { attack: 1, defense: 1, moves: 4, cost: 25 }

  - id: unit_archer
    name: "Archer"
    prompt: "ancient archer, short composite bow drawn, leather armor, quiver of arrows"
    category: military
    era: ancient
    class: ranged
    tags: [military, ranged, ancient]
    stats: { attack: 2, defense: 1, moves: 2, cost: 35, range: 2 }

  - id: unit_spearman
    name: "Spearman"
    prompt: "ancient spearman, bronze-tipped spear, large round hoplon shield, leather armor"
    category: military
    era: ancient
    class: melee
    tags: [military, melee, anti-cavalry, ancient]
    stats: { attack: 2, defense: 3, moves: 2, cost: 45 }

  - id: unit_chariot
    name: "War Chariot"
    prompt: "ancient war chariot, two horses, archer platform, wooden spoked wheels, Egyptian style"
    category: military
    era: ancient
    class: mounted
    tags: [military, mounted, ranged, ancient]
    stats: { attack: 3, defense: 1, moves: 4, cost: 60, range: 1 }

  - id: unit_galley
    name: "Galley"
    prompt: "ancient war galley, single sail, oar banks, bronze ram bow, Mediterranean trireme"
    category: military
    era: ancient
    class: naval
    tags: [military, naval, ancient]
    stats: { attack: 2, defense: 1, moves: 3, cost: 50 }

  # === CLASSICAL ERA ===

  - id: unit_swordsman
    name: "Swordsman"
    prompt: "Roman legionary soldier, gladius sword, rectangular scutum shield, lorica segmentata armor, red cape"
    category: military
    era: classical
    class: melee
    tags: [military, melee, heavy, classical]
    stats: { attack: 4, defense: 3, moves: 2, cost: 75 }

  - id: unit_horseman
    name: "Horseman"
    prompt: "classical cavalry rider, mounted on horse, javelin and small shield, light armor, flowing cloak"
    category: military
    era: classical
    class: mounted
    tags: [military, mounted, fast, classical]
    stats: { attack: 3, defense: 2, moves: 4, cost: 80 }

  - id: unit_catapult
    name: "Catapult"
    prompt: "ancient siege catapult, wooden frame, twisted rope torsion, ammunition pile, crew operating"
    category: military
    era: classical
    class: siege
    tags: [military, siege, classical]
    stats: { attack: 5, defense: 1, moves: 1, cost: 100, range: 3 }

  - id: unit_trireme
    name: "Trireme"
    prompt: "Greek trireme warship, three banks of oars, bronze ram, large square sail, deck soldiers"
    category: military
    era: classical
    class: naval
    tags: [military, naval, classical]
    stats: { attack: 3, defense: 2, moves: 4, cost: 80 }

  # === MEDIEVAL ERA ===

  - id: unit_crossbowman
    name: "Crossbowman"
    prompt: "medieval crossbowman, heavy crossbow, cranequin, padded armor, bolt quiver"
    category: military
    era: medieval
    class: ranged
    tags: [military, ranged, medieval]
    stats: { attack: 4, defense: 2, moves: 2, cost: 90, range: 2 }

  - id: unit_knight
    name: "Knight"
    prompt: "medieval knight, full plate armor, lance couched, caparisoned warhorse, heraldic surcoat"
    category: military
    era: medieval
    class: mounted
    tags: [military, mounted, heavy, medieval]
    stats: { attack: 5, defense: 4, moves: 3, cost: 120 }

  - id: unit_pikeman
    name: "Pikeman"
    prompt: "medieval pikeman, very long pike weapon, morion helmet, breastplate armor, formation stance"
    category: military
    era: medieval
    class: melee
    tags: [military, melee, anti-cavalry, medieval]
    stats: { attack: 3, defense: 4, moves: 2, cost: 85 }

  - id: unit_trebuchet
    name: "Trebuchet"
    prompt: "medieval trebuchet siege engine, counterweight, long throwing arm, wooden frame, massive scale"
    category: military
    era: medieval
    class: siege
    tags: [military, siege, medieval]
    stats: { attack: 8, defense: 1, moves: 1, cost: 150, range: 4 }

  - id: unit_caravel
    name: "Caravel"
    prompt: "medieval caravel ship, lateen sails, forecastle, Portuguese explorer vessel"
    category: military
    era: medieval
    class: naval
    tags: [military, naval, exploration, medieval]
    stats: { attack: 2, defense: 2, moves: 5, cost: 100 }

  # === RENAISSANCE ERA ===

  - id: unit_musketman
    name: "Musketman"
    prompt: "renaissance musketeer, matchlock musket, wide-brimmed hat, colorful uniform, bandolier"
    category: military
    era: renaissance
    class: ranged
    tags: [military, ranged, gunpowder, renaissance]
    stats: { attack: 5, defense: 3, moves: 2, cost: 110, range: 1 }

  - id: unit_lancer
    name: "Lancer"
    prompt: "renaissance lancer cavalry, long lance, plumed helmet, half plate armor, decorated horse"
    category: military
    era: renaissance
    class: mounted
    tags: [military, mounted, renaissance]
    stats: { attack: 5, defense: 3, moves: 4, cost: 130 }

  - id: unit_cannon
    name: "Cannon"
    prompt: "renaissance bronze cannon, wheeled carriage, cannonballs stacked, artillery crew"
    category: military
    era: renaissance
    class: siege
    tags: [military, siege, gunpowder, renaissance]
    stats: { attack: 10, defense: 2, moves: 1, cost: 180, range: 3 }

  - id: unit_frigate
    name: "Frigate"
    prompt: "sailing frigate warship, three masts, gun deck cannons, Age of Sail vessel"
    category: military
    era: renaissance
    class: naval
    tags: [military, naval, renaissance]
    stats: { attack: 5, defense: 4, moves: 5, cost: 150 }

  # === INDUSTRIAL ERA ===

  - id: unit_rifleman
    name: "Rifleman"
    prompt: "19th century rifleman soldier, bolt action rifle, military uniform, kepi cap, bayonet"
    category: military
    era: industrial
    class: ranged
    tags: [military, ranged, industrial]
    stats: { attack: 6, defense: 4, moves: 2, cost: 140, range: 1 }

  - id: unit_cavalry
    name: "Cavalry"
    prompt: "19th century cavalry soldier, saber drawn, military uniform, mounted on horse, carbine"
    category: military
    era: industrial
    class: mounted
    tags: [military, mounted, industrial]
    stats: { attack: 6, defense: 3, moves: 5, cost: 160 }

  - id: unit_artillery
    name: "Artillery"
    prompt: "19th century field artillery, wheeled cannon, limber, artillery crew in uniform"
    category: military
    era: industrial
    class: siege
    tags: [military, siege, industrial]
    stats: { attack: 12, defense: 2, moves: 1, cost: 220, range: 4 }

  - id: unit_ironclad
    name: "Ironclad"
    prompt: "ironclad warship, armored hull, steam funnel, turret guns, Civil War era"
    category: military
    era: industrial
    class: naval
    tags: [military, naval, industrial]
    stats: { attack: 7, defense: 6, moves: 4, cost: 200 }

  # === MODERN ERA ===

  - id: unit_infantry
    name: "Infantry"
    prompt: "modern infantry soldier, assault rifle, combat helmet, tactical vest, camouflage uniform"
    category: military
    era: modern
    class: ranged
    tags: [military, ranged, modern]
    stats: { attack: 8, defense: 5, moves: 2, cost: 180, range: 1 }

  - id: unit_tank
    name: "Tank"
    prompt: "modern main battle tank, large turret cannon, tracked vehicle, reactive armor, powerful"
    category: military
    era: modern
    class: armored
    tags: [military, armored, modern]
    stats: { attack: 10, defense: 8, moves: 3, cost: 300 }

  - id: unit_fighter
    name: "Fighter"
    prompt: "modern fighter jet aircraft, swept wings, twin engines, missiles, sleek design"
    category: military
    era: modern
    class: air
    tags: [military, air, modern]
    stats: { attack: 8, defense: 4, moves: 8, cost: 280, range: 6 }

  - id: unit_battleship
    name: "Battleship"
    prompt: "modern battleship, large gun turrets, radar arrays, armored hull, massive warship"
    category: military
    era: modern
    class: naval
    tags: [military, naval, modern]
    stats: { attack: 12, defense: 8, moves: 4, cost: 350, range: 3 }

  # === CIVILIAN UNITS ===

  - id: unit_settler
    name: "Settler"
    prompt: "pioneer settler group, covered wagon, ox-drawn, supplies loaded, family with tools"
    category: civilian
    era: ancient
    class: civilian
    tags: [civilian, founder]
    stats: { attack: 0, defense: 0, moves: 2, cost: 80 }

  - id: unit_worker
    name: "Worker"
    prompt: "ancient worker laborer, simple tunic, carrying shovel and pickaxe, rope coiled"
    category: civilian
    era: ancient
    class: civilian
    tags: [civilian, builder]
    stats: { attack: 0, defense: 0, moves: 2, cost: 50 }

  - id: unit_great_general
    name: "Great General"
    prompt: "great military general, ornate armor, command baton, cape flowing, heroic pose"
    category: great_person
    era: ancient
    class: great_person
    tags: [great_person, military]
    stats: { attack: 0, defense: 0, moves: 2, cost: 0 }

  - id: unit_great_scientist
    name: "Great Scientist"
    prompt: "great scientist scholar, robes, holding scroll and astrolabe, wise elderly figure"
    category: great_person
    era: ancient
    class: great_person
    tags: [great_person, science]
    stats: { attack: 0, defense: 0, moves: 2, cost: 0 }

  - id: unit_great_artist
    name: "Great Artist"
    prompt: "great artist, flowing robes, holding paintbrush and palette, creative pose"
    category: great_person
    era: ancient
    class: great_person
    tags: [great_person, culture]
    stats: { attack: 0, defense: 0, moves: 2, cost: 0 }

stages:
  - id: generate_meshes
    type: comfyui_batch
    workflow: fab/backbay-imperium/workflows/hunyuan3d_character.json
    settings:
      batch_size: 3
      retry_on_failure: 2
    outputs:
      - "mesh.glb"
      - "preview.png"

  - id: validate_meshes
    type: gate
    requires: [generate_meshes]
    gates:
      - fab/backbay-imperium/gates/unit_v001.yaml
    on_failure: retry

  - id: auto_rig
    type: blender
    requires: [validate_meshes]
    script: fab/backbay-imperium/scripts/auto_rig_unit.py
    settings:
      rig_type: humanoid

  - id: render_sprites
    type: blender
    requires: [auto_rig]
    script: fab/backbay-imperium/scripts/render_unit_sprites.py
    settings:
      directions: 8
      animations: [idle, walk, attack]
      frames_per_animation: 3
      resolution: [64, 64]

  - id: pack_spritesheets
    type: python
    requires: [render_sprites]
    script: fab/backbay-imperium/scripts/pack_unit_spritesheet.py

publish:
  meshes:
    path: fab/backbay-imperium/assets/units/meshes
  sprites:
    path: fab/backbay-imperium/assets/units/sprites
  spritesheets:
    path: fab/backbay-imperium/assets/units/sheets
  manifest:
    path: fab/backbay-imperium/assets/units/manifest.yaml
